name: ${SERVER_NAME=-prominence}

services:
  restore-backup:
    container_name: restore_backup
    image: itzg/mc-backup
    restart: 'no'
    entrypoint: restore-tar-backup
    volumes:
      - volume:/data
      - ./backups:/backups:ro

  server:
    container_name: server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    env_file: .env
    volumes:
      - volume:/data
      - ./logs:/data/logs
      - ./downloads:/downloads
    restart: 'on-failure:1'
    depends_on:
      restore-backup:
        condition: service_completed_successfully

  backups:
    container_name: backups
    image: itzg/mc-backup
    env_file: .env
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - volume:/data:ro
      - ./backups:/backups
      - ./post-backup.sh:/post-backup.sh:ro
  
volumes:
  volume:
    name: ${SERVER_NAME:-COMPOSE_PROJECT_NAME}