version: '1.0'
name: prominence

services:
  server:
    container_name: server
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    env_file: .env
    environment:
      EULA: 'TRUE'
      ONLINE_MODE: 'FALSE'
    volumes:
      - prominence:/data
      - ./logs:/data/logs
      - ./downloads:/downloads
    restart: on-failure
  backups:
    container_name: backups
    image: itzg/mc-backup
    env_file: .env
    environment:
      INITIAL_DELAY: 0
      BACKUP_NAME: 'backup'
      BACKUP_INTERVAL: '1h'
      PRUNE_BACKUPS_DAYS: 2
      PLAYERS_ONLINE_CHECK_INTERVAL: '1m'
      PAUSE_IF_NO_PLAYERS: TRUE
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - prominence:/data:ro
      - ./backups:/backups
  restore-backup:
    container_name: restore_backup
    image: itzg/mc-backup
    restart: 'no'
    entrypoint: restore-tar-backup
    volumes:
      - prominence:/data
      - ./backups:/backups:ro
volumes:
  prominence:
    external: true